name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o bin/kong-ui_amd64-darwin main.go
      - run: GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o bin/kong-ui_arm64-darwin main.go
      - run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/kong-ui_amd64-linux main.go
      - run: sudo apt-get install -y upx
      - run: upx bin/kong-ui_amd64-linux
      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/kong-ui*
          retention-days: 5
