name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - 'v*'
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: .github/workflow/build.yaml
