name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'bin/kong-ui*'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
